# Generated by Django 5.1.7 on 2025-03-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv_files/")),
                ("filename", models.CharField(max_length=255)),
                ("features", models.TextField()),
                ("target", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("RandomForest", "Random Forest"),
                            ("LogisticRegression", "Logistic Regression"),
                            ("LinearRegression", "Linear Regression"),
                            ("SVM", "Support Vector Machine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("mse", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "csv_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="versionning.csv",
                    ),
                ),
            ],
        ),
    ]
