# Generated by Django 5.1.7 on 2025-03-28 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csv',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dataset CSV', 'verbose_name_plural': 'Datasets CSV'},
        ),
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Modèle entraîné', 'verbose_name_plural': 'Modèles entraînés'},
        ),
        migrations.AddField(
            model_name='csv',
            name='column_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csv',
            name='description',
            field=models.TextField(blank=True, help_text='Description optionnelle du dataset', null=True),
        ),
        migrations.AddField(
            model_name='csv',
            name='is_classification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csv',
            name='row_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='feature_importance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='model_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='r2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='training_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='features',
            field=models.TextField(help_text='Liste des colonnes séparées par des virgules'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file',
            field=models.FileField(help_text='Format accepté : CSV uniquement', upload_to='csv_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='algorithm',
            field=models.CharField(choices=[('RandomForest', 'Random Forest'), ('LogisticRegression', 'Logistic Regression'), ('LinearRegression', 'Linear Regression'), ('SVM', 'Support Vector Machine'), ('XGBoost', 'XGBoost'), ('KNN', 'K-Nearest Neighbors')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='csv_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='versionning.csv'),
        ),
    ]
