# Generated by Django 5.1.7 on 2025-03-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionning', '0002_alter_csv_options_alter_trainedmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='categorical_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='csv',
            name='data_types',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='csv',
            name='is_preprocessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csv',
            name='missing_values',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='csv',
            name='numerical_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='csv',
            name='preprocessed_file',
            field=models.FileField(blank=True, null=True, upload_to='preprocessed_files/'),
        ),
        migrations.AddField(
            model_name='csv',
            name='preprocessing_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='csv',
            name='statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='csv',
            name='unique_values',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='csv',
            name='column_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='csv',
            name='features',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='csv',
            name='is_classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='csv',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
    ]
