# Generated by Django 5.1.7 on 2025-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionning', '0003_csv_categorical_columns_csv_data_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='features',
            field=models.TextField(help_text='Liste des colonnes séparées par des virgules'),
        ),
    ]
