# Generated by Django 5.1.7 on 2025-03-28 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionning', '0004_alter_csv_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='description',
        ),
        migrations.AddField(
            model_name='csv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='categorical_columns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='column_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='data_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file',
            field=models.FileField(upload_to='csv_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
        migrations.AlterField(
            model_name='csv',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='csv',
            name='missing_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='numerical_columns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='preprocessing_steps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='row_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='statistics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='target',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='csv',
            name='unique_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
