# Generated by Django 5.1.7 on 2025-03-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionning', '0005_remove_csv_description_csv_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='features',
            field=models.TextField(blank=True, help_text='Liste des colonnes séparées par des virgules', null=True),
        ),
    ]
