# Generated by Django 5.1.7 on 2025-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionning', '0006_alter_csv_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='algorithm',
            field=models.CharField(choices=[('Random Forest', 'Random Forest'), ('Linear Regression', 'Régression Linéaire'), ('Logistic Regression', 'Régression Logistique'), ('SVM', 'Support Vector Machine'), ('XGBoost', 'XGBoost'), ('KNN', 'K-Nearest Neighbors')], max_length=50),
        ),
    ]
